#
# Generate MOK (machine owner key)
#

- name: ansible crypto requirements are installed
  apt:
    name: python3-openssl
    state: present

- name: mokutil is installed
  apt:
    name: mokutil
    state: present

- name: mok private key is created
  openssl_privatekey:
    type: RSA
    size: 2048
    path: /root/mok-privkey.pem
    mode: 0600

- name: mok csr is created
  openssl_csr:
    path: /root/mok-cert.csr
    privatekey_path: /root/mok-privkey.pem
    common_name: "Machine owner key"

- name: mok certificate is created
  openssl_certificate:
    path: /root/mok-cert.der
    csr_path: /root/mok-cert.csr
    privatekey_path: /root/mok-privkey.pem
    provider: selfsigned
    selfsigned_not_after: "+3650d"

#
# DKMS
#

- name: dkms and linux headers are installed
  apt:
    name:
      - dkms
      - "linux-headers-{{ ansible_kernel }}"
    state: present

- name: kmod signing script is up
  copy:
    src: sign-kmod.sh
    dest: /root/sign-kmod.sh
    mode: 0700
