- hosts: rio
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    k3s_address: "{{ wg_subnet | ipaddr(1) }}"

  roles:
    - apt
    - wireguard-server
    - postgres-server
    - k3s-server
    - firewall
