- hosts: rio
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    k3s_address: "{{ wg_subnet | ipaddr(1) | ipaddr('address') }}"
    k3s_version: v0.9.1

  roles:
    - apt
    - admin-user
    - wireguard-server
    - postgres-server
    - k3s-server
    - mackerel
    - firewall
