- name: curl is installed
  apt:
    name: curl
    state: present

- name: k3s is installed
  shell: curl -fsSL https://get.k3s.io/ | sh -
  args:
    creates: /usr/local/bin/k3s
  environment:
    # - tls-san option allows remote kubectl via wireguard
    # - disable traefik as it conflicts with Rio's service loadbalancer
    INSTALL_K3S_EXEC: "server --tls-san {{ k3s_address }} --no-deploy traefik"
    INSTALL_K3S_VERSION: v0.9.1

- name: k3s is started
  service:
    name: k3s
    state: started
    enabled: yes

- name: k3s service port is registered
  lineinfile:
    path: /etc/services
    line: "kubernetes 6443/tcp"
    regexp: "^kubernetes "
    state: present
