- name: curl is installed
  apt:
    name: curl
    state: present

- name: k3s is installed
  shell: curl -fsSL https://get.k3s.io/ | sh -
  args:
    creates: /usr/local/bin/k3s
  environment:
    # - tls-san option allows remote kubectl via wireguard
    # - disable traefik as it conflicts with Rio's service loadbalancer
    INSTALL_K3S_EXEC: "server --tls-san {{ k3s_address }} --no-deploy traefik"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"

- name: k3s is started
  service:
    name: k3s
    state: started
    enabled: yes

- name: k3s service ports are registered
  lineinfile:
    path: /etc/services
    line: "{{ item.name }} {{ item.port }}"
    regexp: "^{{ item.name }} "
    state: present
  with_items:
    - { name: kubernetes, port: 6443/tcp }
    - { name: flannel,    port: 8472/udp }

- name: k3s remote config is generated
  shell: |
    sed                                \
      's/127.0.0.1/{{ k3s_address }}/' \
      /etc/rancher/k3s/k3s.yaml        \
    > k3s-remote.yaml
  warn: no
  changed_when: none

- name: k3s remote config is downloaded
  fetch:
    src: k3s-remote.yaml
    dest: _output/k3s.yaml
    flat: yes
