- name: dkms and linux headers are installed
  apt:
    name:
      - dkms
      - "linux-headers-{{ ansible_kernel }}"
    state: present

- name: wireguard repository is enabled
  apt_repository:
    repo: ppa:wireguard/wireguard
    state: present

# This takes a while to build wireguard kernel module.
- name: wireguard is installed
  apt:
    name: wireguard
    state: present

- name: wireguard bastion configuration is up
  template:
    src: wg-bastion.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0600
  notify: restart wg-quick

- name: wireguard service port is registered
  lineinfile:
    path: /etc/services
    line: "wg0 {{ wg_bastion_port }}/udp"
    regexp: "^wg0 "
    state: present

- name: wireguard kernel module is loaded
  modprobe:
    name: wireguard
    state: present

- name: wg-quick is activated
  service:
    name: wg-quick@wg0
    state: started
    enabled: yes
