- name: ufw is disabled
  service:
    name: ufw
    state: stopped
    enabled: no

- name: iptables persistence packages are installed
  apt:
    name:
      - netfilter-persistent
      - iptables-persistent
    state: present

- name: iptables rules are up
  template:
    src: "{{ inventory_hostname }}/iptables-{{ item }}.j2"
    dest: "/etc/iptables/{{ item }}"
    mode: 0600
  vars:
    PIF: "{{ ansible_default_ipv4.interface }}"
  with_items:
    - rules.v4
    - rules.v6
  notify: restart firewall

- name: firewall is activated
  service:
    name: netfilter-persistent
    state: started
    enabled: yes
