- name: uenv apt repository is added
  apt_repository:
    repo: ppa:snsinfu/uenv
    state: present

- name: uenv is installed
  apt:
    name: uenv
    state: present

- name: wal-g directories are present
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /srv/wal-g
    - /srv/wal-g/bin

- name: wal-g is downloaded
  unarchive:
    src: "https://github.com/wal-g/wal-g/releases/download/{{ walg_version }}/wal-g.linux-amd64.tar.gz"
    dest: /srv/wal-g/bin
    remote_src: yes
    creates: /srv/wal-g/bin/wal-g

- name: wal-g gcs environment is up
  template:
    src: gs.env.j2
    dest: /srv/wal-g/gs.env
    mode: 0640
    owner: root
    group: postgres

- name: gcs service account key is up
  copy:
    src: service_account-backup
    dest: /srv/wal-g/service_account.json
    mode: 0640
    owner: root
    group: postgres

# The cron frequency is set to high for testing purpose.

- name: wal-g backup job script is up
  template:
    src: backup.sh.j2
    dest: /srv/wal-g/backup.sh
    mode: 0755

- name: wal-g backup job is set up
  cron:
    name: daily backup
    user: root
    cron_file: wal-g
    special_time: daily
    job: "uenv -f /srv/wal-g/gs.env /srv/wal-g/backup.sh"

- name: walg backup job variables are set
  cronvar:
    user: root
    cron_file: wal-g
    name: PATH
    value: "/bin:/usr/bin:/srv/wal-g/bin"
